# Copyright (c) 2026 Matthew S. Novak. All rights reserved.
from __future__ import annotations

import copy
import json
import re
import shutil
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any

from . import __version__
from .config import load_config
from .errors import IaTDocsError
from .markdown import strip_legacy_front_matter
from .util import load_json, write_json


def _catalog(root: Path) -> dict[str, Any]:
    value = load_json(root / "ai" / "document-profiles.json")
    if not isinstance(value, dict) or not isinstance(value.get("profiles"), list):
        raise IaTDocsError("ai/document-profiles.json is invalid")
    return value


def _master_modules(path: Path) -> dict[int, tuple[str, str]]:
    text = strip_legacy_front_matter(path.read_text(encoding="utf-8"))
    parts = re.split(r"(?m)^##\s+(\d+)\.\s+(.+?)\s*\n", text)
    modules: dict[int, tuple[str, str]] = {}
    for index in range(1, len(parts), 3):
        modules[int(parts[index])] = (parts[index + 1].strip(), parts[index + 2].strip())
    if not modules:
        raise IaTDocsError(f"no numbered modules found in {path}")
    return modules


def _select(profile: dict[str, Any], mode: str, mandatory: list[int]) -> list[int]:
    required = {int(value) for value in profile.get("required_modules", [])}
    recommended = {int(value) for value in profile.get("recommended_modules", [])}
    optional = {int(value) for value in profile.get("optional_modules", [])}
    selected = required | set(mandatory)
    if mode in {"recommended", "comprehensive"}:
        selected |= recommended
    if mode == "comprehensive":
        selected |= optional
    if mode not in {"minimum", "recommended", "comprehensive"}:
        raise IaTDocsError(f"unsupported generation mode: {mode}")
    return sorted(selected)


def _render(profile: dict[str, Any], mode: str, selected: list[int], modules: dict[int, tuple[str, str]]) -> str:
    lines = [
        f"<!-- Generated by 2210Docs {__version__} from profile {profile['id']} in {mode} mode. -->",
        "<!-- Replace instructional content with verified subject content and remove non-applicable optional modules before release. -->",
        "",
    ]
    for sequence, number in enumerate(selected, start=1):
        if number not in modules:
            raise IaTDocsError(f"profile references missing module {number}")
        title, body = modules[number]
        lines.extend([
            f"<!-- 2210-module: {number:02d} -->",
            f"## {sequence}. {title}",
            "",
            body.rstrip(),
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def initialize_document(
    root: Path,
    *,
    profile_id: str,
    document_id: str,
    title: str,
    source_repository: str,
    mode: str | None = None,
    version: str = "v0.01",
    subtitle: str | None = None,
    summary: str | None = None,
    creator_name: str | None = None,
    creator_account: str | None = None,
    creator_work_ledger_id: str | None = None,
    creator_position_number: str | None = None,
    owner: str | None = None,
    steward: str | None = None,
    created_at: str | None = None,
    review_date: str | None = None,
    ghe_host: str = "enterprise.example.invalid",
    allow_canonical: bool = False,
    apply: bool = False,
) -> dict[str, Any]:
    root = root.resolve()
    if not allow_canonical and any(token in root.name.casefold() for token in ("template", "docs-engine", "engine")):
        raise IaTDocsError(
            "refusing to generate a subject-specific document inside the canonical engine/template path; "
            "create a separate private derived repository first"
        )
    config = load_config(root)
    catalog = _catalog(root)
    profile = next((item for item in catalog["profiles"] if isinstance(item, dict) and item.get("id") == profile_id), None)
    if not profile:
        choices = ", ".join(str(item.get("id")) for item in catalog["profiles"] if isinstance(item, dict))
        raise IaTDocsError(f"unknown profile {profile_id!r}; choices: {choices}")
    selected_mode = mode or str(profile.get("default_mode") or "recommended")
    mandatory = [int(value) for value in catalog.get("mandatory_control_modules", [2, 29, 30, 31, 32])]
    selected = _select(profile, selected_mode, mandatory)
    modules = _master_modules(root / "section-library" / "2210-master.md")
    content = _render(profile, selected_mode, selected, modules)

    document_path = config.path(config.paths.document_data, "document_data")
    revisions_path = config.path(config.paths.revisions_data, "revisions_data")
    content_path = config.path(f"{config.paths.content_dir}/{config.build.content_files[0]}", "content file")
    document = load_json(document_path)
    if not isinstance(document, dict):
        raise IaTDocsError("document metadata must be a JSON object")
    document = copy.deepcopy(document)
    created = created_at or date.today().isoformat()
    document.update({
        "document_id": document_id,
        "document_type": str(profile.get("document_type") or profile.get("name") or "2210 CONTROLLED DOCUMENT"),
        "document_profile": profile_id,
        "title": title,
        "subtitle": subtitle or f"Controlled {profile.get('name', '2210 document')}",
        "summary": summary or str(profile.get("purpose") or "Controlled 2210 document generated from the canonical contract."),
        "version": version,
        "status": "Draft",
        "visibility": "Internal",
        "owner": owner or "REQUIRED — NOT YET PROVIDED",
        "steward": steward or "REQUIRED — NOT YET PROVIDED",
        "effective_date": "Not effective",
        "last_review_date": created,
        "review_date": review_date or "REQUIRED — NOT YET PROVIDED",
        "source_repository": source_repository,
        "repository_url": "",
        "ghe_host": ghe_host,
        "source_branch": "main",
        "content_path": f"{config.paths.content_dir}/{config.build.content_files[0]}",
        "edit_url": "",
        "template_version": f"v{__version__}",
        "engine_version": __version__,
        "contribution_paths": [
            f"{config.paths.content_dir}/{config.build.content_files[0]}",
            config.paths.document_data,
            config.paths.revisions_data,
            config.paths.attachments_dir,
        ],
        "use_restriction": (
            "This controlled draft does not independently authorize operational execution, access, or change. "
            "Required facts, approvals, evidence, effective status, and release gates must be complete before use."
        ),
        "footer_text": "Controlled 2210 document rendered by 2210Docs from repository source. Use the live Pages site as the authoritative reading copy.",
    })
    document["creator"] = {
        "name": creator_name or "REQUIRED — NOT YET PROVIDED",
        "account": creator_account or "REQUIRED — NOT YET PROVIDED",
        "work_ledger_id": creator_work_ledger_id or "REQUIRED — NOT YET PROVIDED",
        "position_number": creator_position_number or "REQUIRED — NOT YET PROVIDED",
        "created_at": created,
        "aliases": [],
    }
    revisions = {
        "schema_version": 1,
        "entries": [{
            "version": version,
            "date": created,
            "status": "Draft",
            "editor": creator_name or "Document creator — not yet provided",
            "reviewer": "Technical reviewer pending",
            "approver": "Approval pending",
            "summary": f"Initial {profile_id} controlled draft created by 2210Docs.",
            "reference": "Initial repository draft",
            "reference_url": "",
        }],
    }
    plan = {
        "status": "planned" if not apply else "applied",
        "profile": profile_id,
        "mode": selected_mode,
        "modules": selected,
        "section_count": len(selected),
        "target": str(root),
        "files": [str(content_path), str(document_path), str(revisions_path)],
    }
    if not apply:
        return plan

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    backup = root / ".template-backup" / f"iatdocs-init-{stamp}"
    for source in (content_path, document_path, revisions_path):
        if source.exists():
            destination = backup / source.relative_to(root)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
    content_path.parent.mkdir(parents=True, exist_ok=True)
    content_path.write_text(content, encoding="utf-8", newline="\n")
    write_json(document_path, document)
    write_json(revisions_path, revisions)
    plan["backup"] = str(backup)
    return plan
